services:
  example_talker:
    build:
      context: .
      args:
        PACKAGE_NAME: example
      target: example_talker
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID=100
    command: /bin/bash -c 'source /workspace/install/setup.bash && exec ros2 run example talker'

  example_listener:
    build:
      context: .
      args:
        PACKAGE_NAME: example
      target: example_listener
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID=100
    command: /bin/bash -c 'source /workspace/install/setup.bash && exec ros2 run example listener'
