ARG ROS_DISTRO=humble


FROM ros:${ROS_DISTRO}-ros-base

ARG UID
ARG GID

RUN groupadd -g ${GID} user && \
    useradd -m -s /bin/bash -u ${UID} -g ${GID} user

# When using the shell in a development environment, do not execute it manually.
# Not needed in production (already setup in the base image).
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/user/.bashrc

USER user
WORKDIR /home/user/ros2_ws/
